name: vega-altair-demo-002
channels:
  - conda-forge
dependencies:
  - python=3.10
  - altair==4.2.2
  - vega
  - jupyterlab
  - pip
  - pip:
      - delta-sharing
      - altair_transform==0.2.0
      - vegafusion[embed]==1.1.2
      - vegafusion-jupyter[embed]==1.1.2